### ISSUE TITLE
Peer to peer code

### ISSUE THREAD

**Issue by ichsansandy** [batoolfatima2135/To-do-List-App#7]
Hi Fatima 
Congratulations for your approved code 🎉 🎉 🎉 
**But**
We would like to suggest some improvement about your checked.js function here

https://github.com/batoolfatima2135/To-do-List-App/blob/817b55651c0970818e3f5fe523936eb4519703e6/src/modules/checked.js#L1-L10

You can refactor it to

```js
export default function updateChecked(tasks, index) {
  tasks.map((item) => {
    if (item.index === index) {
      if (item.completed === false) {
        item.completed = true;
      } else {
        item.completed = false;
      }
    }
    return item;
  });
  localStorage.setItem('tasks', JSON.stringify(tasks));
}
```

Please do it in your own risk 😃

**Comment by batoolfatima2135** [comment]
hey @ichsansandy !
Thank you so much for the suggestion 👍  😀 
I really appreciate for time and effort.
I have successfully updated my file `checked.js` with your wonderful suggestion
https://github.com/batoolfatima2135/To-do-List-App/blob/472d86b63b8115621ee678c30bd30e84dcbae1ea/src/modules/checked.js#L1-L13
;
Thank you once again for the suggestion. 👍  Keep supporting 💯  
Happy Coding 😊
